# CIE-IVI
IVI Project done under CIE

Problems Faced:
1. Had problems running repo on a system with Python 2.7
    
	use the command:<br>
		python3 /home/cie/bin/repo ...<br>
	instead of:<br>
		repo init ...<br>
   
3. Repo sync is failing<br>
	repo sync was successful until 93% completion was hi.<br>
	The following were the errors:<br>
	
 ![image description](Screenshot%20from%202024-01-29%2015-49-07.png)
