# CIE-IVI
IVI Project done under CIE

Problems Faced:
1. Had problems running repo on a system with Python 2.7
    
	use the command:<br>
		python3 /home/cie/bin/repo init ...<br>
	instead of:<br>
		repo init ...<br>
   
3. Repo sync is failing<br>
	repo sync ran successfully until 93% completion.<br>
 
	Following errors occured thereafter:<br>
 	The complete error log can be inspected here: [repo_sync_error_log.txt](repo_sync_error_log.txt)<br>
	
 ![image description](Screenshot%20from%202024-01-29%2015-49-07.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-15.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-22.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-30.png)
 ![image description](Screenshot%20from%202024-01-29%2015-49-40.png)
 
