# CIE-IVI
IVI Project done under CIE

Problems Faced:
1. Had problems running repo on a system with Python 2.7
    
	use the command:
		python3 /home/cie/bin/repo ...
	instead of:
		repo init ...
   
3. Repo sync is failing
	repo sync was successful until 93% completion was hi.
	The following were the errors:
	
 ![image description](Screenshot%20from%202024-01-29%2015-49-07.png)
